/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        "primary-focus": "var(--color-primary-focus)",
        "primary-content": "var(--color-primary-content)",
        secondary: "var(--color-secondary)",
        "secondary-focus": "var(--color-secondary-focus)",
        "secondary-content": "var(--color-secondary-content)",
        accent: "var(--color-accent)",
        "accent-focus": "var(--color-accent-focus)",
        "accent-content": "var(--color-accent-content)",
        neutral: "var(--color-neutral)",
        "neutral-focus": "var(--color-neutral-focus)",
        "neutral-content": "var(--color-neutral-content)",
        "base-100": "var(--color-base-100)",
        "base-200": "var(--color-base-200)",
        "base-300": "var(--color-base-300)",
        "base-content": "var(--color-base-content)",
        info: "var(--color-info)",
        "info-content": "var(--color-info-content)",
        success: "var(--color-success)",
        "success-content": "var(--color-success-content)",
        warning: "var(--color-warning)",
        "warning-content": "var(--color-warning-content)",
        error: "var(--color-error)",
        "error-content": "var(--color-error-content)",

        // automatorsPurple: "rgba(72, 43, 124, 1)",
        // automatorsPurpleHover: "rgba(51, 23, 104, 1)",
        // automatorsPurpleFocus: "rgba(31, 13, 84, 1)",
        // automatorsTourquoise: "rgba(69, 156, 167,1)",
        // automatorsTourquoiseHover: "rgba(49, 136, 147,1)",
        // automatorsTourquoiseFocus: "rgba(29, 116, 127,1)",
        // automatorsPurpleLightHover: "rgba(71, 43, 124, 0.1)",
        // automatorsLightHover: "rgba(246,243,250)",
        // borderColor: "rgb(129, 130, 165)",
        // automatorsRed: "rgba(244, 98, 86, 1)",
        // automatorsBlue: "rgba(29, 30, 57, 1)",
        // automatorsBtnHover: "rgba(237, 237, 237, 1)",
        // whiteText: "#ffffff",
        // grayHover: "rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [],
};
