# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependecies
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
        cache: 'npm'
    - uses: pnpm/action-setup@v2
      name: Install pnpm
    - name: Run Linter
      run: pnpm lint
    - name: Run formatter
      run: pnpm format
    - name: Run build
      run: pnpm run build
